version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api-securescan.techflowlabs.gr
    ports:
      - "8082:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://api-securescan.techflowlabs.gr
