import { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  ShieldCheck, Search, Box, FileCode2, Bot,
  CheckCircle2, XCircle, Loader2, AlertTriangle,
  Code, Terminal, Key, History, ChevronDown, ChevronRight,
  User, Lock, LogOut, Trash2,
  ArrowUpDown, SlidersHorizontal, Package,
  TrendingUp, TrendingDown, Minus, Copy, ExternalLink, Download,
} from 'lucide-react';
import confetti from 'canvas-confetti';

import './index.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const SEVERITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatTimestamp(iso) {
  try {
    return new Date(iso).toLocaleString(undefined, {
      year: 'numeric', month: 'short', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });
  } catch { return iso; }
}

function vulnKey(v) { return v.cve_id || `${v.package_name}@${v.version}`; }

function computeDelta(prevScan, currScan) {
  const prevKeys = new Set((prevScan?.vulnerabilities || []).map(vulnKey));
  const currKeys = new Set((currScan?.vulnerabilities || []).map(vulnKey));
  return {
    newVulns:   currScan.vulnerabilities.filter(v => !prevKeys.has(vulnKey(v))),
    fixedVulns: (prevScan?.vulnerabilities || []).filter(v => !currKeys.has(vulnKey(v))),
  };
}

function getSeverityCounts(vulns) {
  return {
    critical: vulns.filter(v => v.severity?.toLowerCase() === 'critical').length,
    high:     vulns.filter(v => v.severity?.toLowerCase() === 'high').length,
    medium:   vulns.filter(v => v.severity?.toLowerCase() === 'medium').length,
    low:      vulns.filter(v => v.severity?.toLowerCase() === 'low').length,
  };
}

function generateMarkdown(repoUrl, results, allVulns) {
  const ts = new Date().toLocaleString();
  const projectTypes = results?.project_types?.join(', ') || 'Unknown';
  const counts = getSeverityCounts(allVulns);
  let md = `# SecureScan Report\n\n`;
  md += `**Repository:** ${repoUrl}  \n`;
  md += `**Scanned:** ${ts}  \n`;
  md += `**Project types:** ${projectTypes}\n\n`;
  md += `## Summary\n\n| Severity | Count |\n|---|---|\n`;
  md += `| 🔴 Critical | ${counts.critical} |\n`;
  md += `| 🟠 High | ${counts.high} |\n`;
  md += `| 🟣 Medium | ${counts.medium} |\n`;
  md += `| 🔵 Low | ${counts.low} |\n`;
  md += `| **Total** | **${allVulns.length}** |\n\n`;
  if (allVulns.length > 0) {
    md += `## Vulnerabilities\n\n`;
    const order = ['critical', 'high', 'medium', 'low'];
    const grouped = {};
    for (const v of allVulns) {
      const sev = v.severity?.toLowerCase() || 'unknown';
      (grouped[sev] = grouped[sev] || []).push(v);
    }
    for (const sev of order) {
      if (!grouped[sev]?.length) continue;
      md += `### ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${grouped[sev].length})\n\n`;
      for (const v of grouped[sev]) {
        md += `#### ${v.package_name} v${v.version}\n`;
        if (v.cve_id) md += `- **CVE:** [${v.cve_id}](https://nvd.nist.gov/vuln/detail/${v.cve_id})\n`;
        md += `- **Scanner:** ${v.scanner_type || 'Unknown'}\n`;
        md += `- **Description:** ${v.description}\n\n`;
      }
    }
  } else {
    md += `## ✅ No vulnerabilities found\n\n`;
  }
  if (results?.results?.ai_review?.ai_output) {
    md += `## AI Code Review\n\n${results.results.ai_review.ai_output}\n\n`;
  }
  md += `---\n*Generated by SecureScan*\n`;
  return md;
}

function generateCSV(allVulns) {
  const headers = ['Package', 'Version', 'Severity', 'CVE ID', 'Scanner', 'Description'];
  const esc = (s) => `"${String(s || '').replace(/"/g, '""')}"`;
  const rows = allVulns.map(v =>
    [v.package_name, v.version, v.severity, v.cve_id || '', v.scanner_type || '', v.description].map(esc).join(',')
  );
  return [headers.map(esc).join(','), ...rows].join('\n');
}

function downloadFile(content, filename, mime) {
  const url = URL.createObjectURL(new Blob([content], { type: mime }));
  Object.assign(document.createElement('a'), { href: url, download: filename }).click();
  URL.revokeObjectURL(url);
}

// ─── Hooks ───────────────────────────────────────────────────────────────────

function useCountUp(target, duration = 1100) {
  const [val, setVal] = useState(0);
  useEffect(() => {
    if (target === 0) { setVal(0); return; }
    let start = null;
    const step = (ts) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / duration, 1);
      setVal(Math.round((1 - Math.pow(1 - p, 4)) * target));
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [target, duration]);
  return val;
}

function useScrollReveal(threshold = 0.12) {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) { setVisible(true); obs.unobserve(el); }
    }, { threshold });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return [ref, visible];
}

// ─── Shared UI ────────────────────────────────────────────────────────────────

function AmbientBackground() {
  return (
    <>
      <div className="ambient-orb ambient-orb-1" />
      <div className="ambient-orb ambient-orb-2" />
      <div className="ambient-orb ambient-orb-3" />
    </>
  );
}

function AnimatedNumber({ value }) {
  return <>{useCountUp(value)}</>;
}

function RevealCard({ children, delay = 0, className = '', style = {} }) {
  const [ref, visible] = useScrollReveal();
  return (
    <div
      ref={ref}
      className={`${visible ? 'reveal-visible' : 'reveal-hidden'} ${className}`}
      style={{ ...style, transitionDelay: `${delay}s` }}
    >
      {children}
    </div>
  );
}

function SkeletonLoader() {
  return (
    <div className="skeleton-list">
      {[0, 1, 2].map(i => (
        <div key={i} className="skeleton-block">
          <div className="skeleton-line skeleton-short" />
          <div className="skeleton-line skeleton-long" />
          <div className="skeleton-line skeleton-medium" />
          <div className="skeleton-line skeleton-xshort" style={{ marginTop: '0.4rem' }} />
        </div>
      ))}
    </div>
  );
}

function AIMarkdown({ children }) {
  return (
    <div className="ai-content">
      <ReactMarkdown remarkPlugins={[remarkGfm]}>{children}</ReactMarkdown>
    </div>
  );
}

function copyText(text) {
  navigator.clipboard.writeText(text).catch(() => {});
  window.dispatchEvent(new CustomEvent('app:toast', { detail: { message: `Copied: ${text}` } }));
}

function VulnCard({ vuln, isNew = false }) {
  const sev = vuln.severity?.toLowerCase() || 'high';
  const handleCardClick = () => {
    if (vuln.cve_id) window.open(`https://nvd.nist.gov/vuln/detail/${vuln.cve_id}`, '_blank', 'noopener,noreferrer');
  };
  return (
    <div
      className={`vuln-card vuln-${sev}${isNew ? ' vuln-card-new' : ''}${vuln.cve_id ? ' vuln-card-link' : ''}`}
      onClick={vuln.cve_id ? handleCardClick : undefined}
    >
      {isNew && <span className="vuln-new-badge">NEW</span>}
      {vuln.cve_id && <ExternalLink size={13} className="vuln-external-icon" />}
      <div className="vuln-header">
        <div>
          <div className="vuln-pkg-row">
            <span className="vuln-pkg">{vuln.package_name}</span>
            <button className="copy-btn" onClick={(e) => { e.stopPropagation(); copyText(vuln.package_name); }} title="Copy package name">
              <Copy size={11} />
            </button>
          </div>
          <div className="vuln-version">v{vuln.version}</div>
        </div>
        <span className={`severity-badge badge-${sev}`}>{vuln.severity}</span>
      </div>
      <p className="vuln-desc">{vuln.description}</p>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1rem' }}>
        {vuln.cve_id ? (
          <div className="vuln-cve-row">
            <a href={`https://nvd.nist.gov/vuln/detail/${vuln.cve_id}`} target="_blank" rel="noopener noreferrer"
               className="vuln-cve" onClick={(e) => e.stopPropagation()}>
              {vuln.cve_id}
            </a>
            <button className="copy-btn" onClick={(e) => { e.stopPropagation(); copyText(vuln.cve_id); }} title="Copy CVE ID">
              <Copy size={11} />
            </button>
          </div>
        ) : (
          <span className="vuln-cve" style={{ opacity: 0.5 }}>No CVE</span>
        )}
        <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px' }}>
          {vuln.scanner_type || 'Unknown'}
        </span>
      </div>
    </div>
  );
}

function SeverityChips({ vulnerabilities }) {
  const c = getSeverityCounts(vulnerabilities);
  if (vulnerabilities.length === 0) return <span className="sev-chip sev-clean">✓ Clean</span>;
  return (
    <div className="severity-chips">
      {c.critical > 0 && <span className="sev-chip sev-critical">{c.critical}C</span>}
      {c.high     > 0 && <span className="sev-chip sev-high">{c.high}H</span>}
      {c.medium   > 0 && <span className="sev-chip sev-medium">{c.medium}M</span>}
      {c.low      > 0 && <span className="sev-chip sev-low">{c.low}L</span>}
    </div>
  );
}

function TrendBadge({ scans }) {
  if (scans.length < 2) return <span className="trend-badge trend-baseline">First scan</span>;
  const { newVulns, fixedVulns } = computeDelta(scans[scans.length - 2], scans[scans.length - 1]);
  const net = newVulns.length - fixedVulns.length;
  if (net > 0)             return <span className="trend-badge trend-worse"><TrendingUp size={12} /> +{newVulns.length} new</span>;
  if (net < 0)             return <span className="trend-badge trend-better"><TrendingDown size={12} /> {fixedVulns.length} fixed</span>;
  if (newVulns.length > 0) return <span className="trend-badge trend-mixed"><Minus size={12} /> {newVulns.length} changed</span>;
  return <span className="trend-badge trend-same"><Minus size={12} /> No change</span>;
}

function VulnFilterBar({ allVulns, filterSeverity, setFilterSeverity, sortBy, setSortBy }) {
  const counts = {
    all:      allVulns.length,
    critical: allVulns.filter(v => v.severity?.toLowerCase() === 'critical').length,
    high:     allVulns.filter(v => v.severity?.toLowerCase() === 'high').length,
    medium:   allVulns.filter(v => v.severity?.toLowerCase() === 'medium').length,
    low:      allVulns.filter(v => v.severity?.toLowerCase() === 'low').length,
  };
  return (
    <div className="vuln-filter-bar">
      <div className="vuln-filter-left">
        <span className="vuln-filter-label"><SlidersHorizontal size={14} /> Filter</span>
        {[{ key: 'all', label: 'All' }, { key: 'critical', label: 'Critical' }, { key: 'high', label: 'High' }, { key: 'medium', label: 'Medium' }, { key: 'low', label: 'Low' }].map(({ key, label }) =>
          (counts[key] > 0 || key === 'all') ? (
            <button key={key} className={`vuln-pill vuln-pill-${key} ${filterSeverity === key ? 'active' : ''}`} onClick={() => setFilterSeverity(key)}>
              {label}<span className="vuln-pill-count">{counts[key]}</span>
            </button>
          ) : null
        )}
      </div>
      <div className="vuln-filter-right">
        <span className="vuln-filter-label"><ArrowUpDown size={14} /> Sort</span>
        <button className={`vuln-sort-btn ${sortBy === 'severity' ? 'active' : ''}`} onClick={() => setSortBy('severity')}>Severity</button>
        <button className={`vuln-sort-btn ${sortBy === 'name' ? 'active' : ''}`} onClick={() => setSortBy('name')}>Package A–Z</button>
      </div>
    </div>
  );
}

// ─── Sparkline ───────────────────────────────────────────────────────────────

function Sparkline({ scans, width = 88, height = 34 }) {
  const values = scans.map(s => s.vulnerabilities.length);
  if (values.length < 2) return null;
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const pad = 4;
  const pts = values.map((v, i) => {
    const x = ((i / (values.length - 1)) * (width - pad * 2) + pad).toFixed(1);
    const y = (height - pad - ((v - min) / range) * (height - pad * 2)).toFixed(1);
    return `${x},${y}`;
  });
  const last = values[values.length - 1];
  const prev = values[values.length - 2];
  const color = last > prev ? '#ff7b72' : last < prev ? '#3fb950' : '#58a6ff';
  const [lx, ly] = pts[pts.length - 1].split(',');
  return (
    <svg width={width} height={height} className="sparkline" style={{ overflow: 'visible' }}>
      <polyline points={pts.join(' ')} fill="none" stroke={color}
        strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" opacity="0.72" />
      <circle cx={lx} cy={ly} r="3" fill={color} />
    </svg>
  );
}

// ─── Severity Donut ───────────────────────────────────────────────────────────

function SeverityDonut({ critical, high, medium, low }) {
  const total = critical + high + medium + low;
  const cx = 40, cy = 40, r = 30, sw = 9;
  const circ = 2 * Math.PI * r;
  const segs = [
    { count: critical, color: '#ff7b72' },
    { count: high,     color: '#ffa657' },
    { count: medium,   color: '#d2a8ff' },
    { count: low,      color: '#a5d6ff' },
  ];
  let cumAngle = 0;
  return (
    <div className="metric-card donut-card">
      <div className="donut-wrap">
        <svg width={80} height={80} viewBox="0 0 80 80">
          <circle cx={cx} cy={cy} r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth={sw} />
          {total > 0 && segs.map(({ count, color }) => {
            if (count === 0) { cumAngle += (count / total) * 360; return null; }
            const dash = (count / total) * circ;
            const el = (
              <circle key={color} cx={cx} cy={cy} r={r} fill="none"
                stroke={color} strokeWidth={sw}
                strokeDasharray={`${dash.toFixed(2)} ${(circ - dash).toFixed(2)}`}
                strokeDashoffset={(circ / 4).toFixed(2)}
                transform={`rotate(${cumAngle}, ${cx}, ${cy})`}
              />
            );
            cumAngle += (count / total) * 360;
            return el;
          })}
        </svg>
        <div className="donut-center">
          {total === 0
            ? <><span className="donut-total" style={{ color: 'var(--success)', fontSize: '1.1rem' }}>✓</span><span className="donut-label">clean</span></>
            : <><span className="donut-total">{total}</span><span className="donut-label">issues</span></>}
        </div>
      </div>
    </div>
  );
}

// ─── Toast ───────────────────────────────────────────────────────────────────

function Toast({ message }) {
  if (!message) return null;
  return (
    <div className="toast">
      <CheckCircle2 size={14} />
      {message}
    </div>
  );
}

// ─── Scan Progress Bar ───────────────────────────────────────────────────────

function ScanProgressBar({ active }) {
  return <div className={`scan-progress-bar${active ? ' scan-progress-active' : ''}`} />;
}

// ─── Export Bar ──────────────────────────────────────────────────────────────

function ExportBar({ repoUrl, results, allVulns }) {
  if (!results) return null;
  const slug = repoUrl.replace(/https?:\/\//, '').replace(/[^a-z0-9]/gi, '-').replace(/-+/g, '-').toLowerCase();
  const ts = new Date().toISOString().slice(0, 10);

  const handleMarkdown = () => {
    downloadFile(generateMarkdown(repoUrl, results, allVulns), `securescan-${slug}-${ts}.md`, 'text/markdown');
    window.dispatchEvent(new CustomEvent('app:toast', { detail: { message: 'Markdown report downloaded' } }));
  };

  const handleCSV = () => {
    if (allVulns.length === 0) {
      window.dispatchEvent(new CustomEvent('app:toast', { detail: { message: 'No vulnerabilities to export' } }));
      return;
    }
    downloadFile(generateCSV(allVulns), `securescan-${slug}-${ts}.csv`, 'text/csv');
    window.dispatchEvent(new CustomEvent('app:toast', { detail: { message: 'CSV downloaded' } }));
  };

  return (
    <div className="export-bar">
      <span className="export-label">Export:</span>
      <button className="export-btn" onClick={handleMarkdown} title="Download full report as Markdown">
        <Download size={13} /> Markdown
      </button>
      <button className={`export-btn export-btn-csv${allVulns.length === 0 ? ' export-btn-disabled' : ''}`}
        onClick={handleCSV} title="Download vulnerabilities as CSV">
        <Download size={13} /> CSV
      </button>
    </div>
  );
}

// ─── Navigation Bar ───────────────────────────────────────────────────────────

function NavBar({ view, onNavigate, onLogout, hidden }) {
  const tabs = [
    { id: 'scanner',  label: 'Scanner',         icon: <ShieldCheck size={15} />, cls: 'nav-tab-scanner' },
    { id: 'history',  label: 'AI History',       icon: <History size={15} />,     cls: 'nav-tab-history' },
    { id: 'packages', label: 'Package History',  icon: <Package size={15} />,     cls: 'nav-tab-packages' },
  ];
  return (
    <nav className={`nav-bar${hidden ? ' nav-hidden' : ''}`}>
      <div className="nav-logo">
        <ShieldCheck size={18} color="#58a6ff" />
        <span>SecureScan</span>
      </div>
      <div className="nav-tabs">
        {tabs.map(({ id, label, icon, cls }) => (
          <button
            key={id}
            className={`nav-tab ${cls} ${view === id ? 'active' : ''}`}
            onClick={() => onNavigate(id)}
          >
            {icon}{label}
          </button>
        ))}
      </div>
      <button className="nav-sign-out" onClick={onLogout}>
        <LogOut size={15} /><span>Sign Out</span>
      </button>
    </nav>
  );
}

// ─── Login Page ───────────────────────────────────────────────────────────────

function LoginPage({ onLogin }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    const credentials = btoa(`${username}:${password}`);
    try {
      const res = await fetch(`${API_URL}/history`, { headers: { 'Authorization': `Basic ${credentials}` } });
      if (res.status === 401) setError('Invalid username or password. Please try again.');
      else onLogin(credentials);
    } catch {
      setError('Connection failed. Check your network and try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-card">
        <div className="login-glow" />
        <div className="login-header">
          <div className="login-icon"><ShieldCheck size={36} color="#58a6ff" /></div>
          <h1 className="logo login-title">SecureScan</h1>
          <p className="subtitle" style={{ fontSize: '1rem' }}>Sign in to access the security scanner</p>
        </div>
        <form onSubmit={handleSubmit} className="login-form">
          <div className="input-wrapper">
            <User className="input-icon" size={20} />
            <input type="text" className="repo-input" placeholder="Username" value={username}
              onChange={e => setUsername(e.target.value)} disabled={loading} required autoComplete="username" autoFocus />
          </div>
          <div className="input-wrapper">
            <Lock className="input-icon" size={20} />
            <input type={showPassword ? 'text' : 'password'} className="repo-input" placeholder="Password"
              value={password} onChange={e => setPassword(e.target.value)} disabled={loading} required
              autoComplete="current-password" style={{ paddingRight: '3.5rem' }} />
            <button type="button" className="show-password-btn" onClick={() => setShowPassword(v => !v)} tabIndex={-1}>
              {showPassword ? '🙈' : '👁'}
            </button>
          </div>
          {error && <div className="login-error"><AlertTriangle size={15} />{error}</div>}
          <button type="submit" className={`scan-btn login-btn ${loading ? 'scanning' : ''}`}
            disabled={loading || !username || !password}>
            {loading ? <><Loader2 size={20} className="loader" /> Signing in…</> : <><ShieldCheck size={20} /> Sign In</>}
          </button>
        </form>
        <p className="login-footer">Protected by SecureScan Basic Auth</p>
      </div>
    </div>
  );
}

// ─── AI Review History ────────────────────────────────────────────────────────

function PreviousReviewItem({ review, index, total }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="ai-review-card" style={{ marginBottom: '0.75rem', borderColor: 'rgba(210,168,255,0.2)' }}>
      <button onClick={() => setOpen(o => !o)} style={{
        display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'none', border: 'none',
        cursor: 'pointer', color: '#d2a8ff', width: '100%', padding: '0.75rem 1rem', fontSize: '0.9rem', fontWeight: 600,
      }}>
        {open ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
        Scan {index + 1} of {total} — {formatTimestamp(review.timestamp)}
      </button>
      {open && (
        <div style={{ padding: '0 1rem 1rem', borderTop: '1px solid rgba(210,168,255,0.15)' }}>
          <AIMarkdown>{review.ai_output}</AIMarkdown>
        </div>
      )}
    </div>
  );
}

function RepoHistoryBlock({ repoUrl, reviews, onDelete, revealDelay, onReScan }) {
  const [collapsed, setCollapsed] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleting, setDeleting] = useState(false);

  const handleDelete = async () => {
    setDeleting(true);
    try { await onDelete(repoUrl); }
    finally { setDeleting(false); setConfirmDelete(false); }
  };

  return (
    <RevealCard delay={revealDelay}>
      <div className="repo-history-block">
        <div className="repo-history-header-row">
          <button className="repo-history-header" onClick={() => setCollapsed(c => !c)}>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
              {collapsed ? <ChevronRight size={18} /> : <ChevronDown size={18} />}
              <span className="repo-history-url">{repoUrl}</span>
            </span>
            <span className="repo-history-count">{reviews.length} scan{reviews.length !== 1 ? 's' : ''}</span>
          </button>
          <div className="repo-delete-area">
            {onReScan && !confirmDelete && (
              <button className="repo-rescan-btn" onClick={(e) => { e.stopPropagation(); onReScan(repoUrl); }} title="Scan again">
                <Search size={12} />Scan again
              </button>
            )}
            {confirmDelete ? (
              <>
                <span className="repo-delete-confirm-text">Delete all scans?</span>
                <button className="repo-delete-btn repo-delete-confirm" onClick={handleDelete} disabled={deleting}>
                  {deleting ? <Loader2 size={13} className="loader" /> : 'Yes, delete'}
                </button>
                <button className="repo-delete-btn repo-delete-cancel" onClick={() => setConfirmDelete(false)} disabled={deleting}>Cancel</button>
              </>
            ) : (
              <button className="repo-delete-btn repo-delete-idle" onClick={() => setConfirmDelete(true)} title="Delete history">
                <Trash2 size={15} />
              </button>
            )}
          </div>
        </div>
        {!collapsed && (
          <div style={{ padding: '0 1.5rem 1.5rem' }}>
            {reviews.map((review, i) => (
              <PreviousReviewItem key={i} review={review} index={i} total={reviews.length} />
            ))}
          </div>
        )}
      </div>
    </RevealCard>
  );
}

function HistoryView({ apiFetch, onReScan }) {
  const [repos, setRepos] = useState(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState(null);
  const [search, setSearch] = useState('');

  useEffect(() => {
    apiFetch('/history')
      .then(r => { if (!r.ok) throw new Error('Failed to load history'); return r.json(); })
      .then(data => { setRepos(data.repos); setLoading(false); })
      .catch(e => { setErr(e.message); setLoading(false); });
  }, []);

  const handleDelete = async (repoUrl) => {
    await apiFetch(`/history?repo_url=${encodeURIComponent(repoUrl)}`, { method: 'DELETE' });
    setRepos(prev => prev.filter(r => r.repo_url !== repoUrl));
  };

  const filtered = repos ? repos.filter(r => r.repo_url.toLowerCase().includes(search.toLowerCase())) : [];

  return (
    <div className="app-container">
      <header>
        <h1 className="logo"><History size={40} color="#d2a8ff" />AI Review History</h1>
        <p className="subtitle">All stored AI security reviews across every scanned repository</p>
      </header>
      {loading && <SkeletonLoader />}
      {err && <div className="dashboard"><div className="status-card" style={{ borderColor: 'rgba(255,123,114,0.3)' }}>
        <div className="status-icon-wrapper" style={{ color: '#ff7b72', background: 'rgba(255,123,114,0.1)' }}><AlertTriangle size={24} /></div>
        <div className="status-info"><h3>Error</h3><p style={{ color: '#ff7b72' }}>{err}</p></div>
      </div></div>}
      {repos && repos.length === 0 && <div style={{ textAlign: 'center', color: 'var(--text-muted)', marginTop: '6rem' }}>
        <Bot size={48} style={{ opacity: 0.3, marginBottom: '1rem' }} />
        <p style={{ fontSize: '1.2rem' }}>No AI reviews saved yet.</p>
        <p style={{ marginTop: '0.5rem', fontSize: '0.95rem' }}>Run a scan first to build up your history.</p>
      </div>}
      {repos && repos.length > 0 && (
        <>
          <div className="history-search-bar">
            <Search size={15} className="history-search-icon" />
            <input
              className="history-search-input"
              placeholder={`Search ${repos.length} repositor${repos.length !== 1 ? 'ies' : 'y'}…`}
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
            {search && <button className="history-search-clear" onClick={() => setSearch('')}>✕</button>}
          </div>
          {filtered.length === 0
            ? <div style={{ textAlign: 'center', color: 'var(--text-muted)', marginTop: '4rem' }}>
                <p>No repos match "{search}"</p>
              </div>
            : <div className="history-list">
                {filtered.map((item, i) => (
                  <RepoHistoryBlock key={item.repo_url} repoUrl={item.repo_url} reviews={item.reviews}
                    onDelete={handleDelete} revealDelay={i * 0.07} onReScan={onReScan} />
                ))}
              </div>}
        </>
      )}
    </div>
  );
}

// ─── Package Vulnerability History ───────────────────────────────────────────

function FixedVulnRow({ vuln }) {
  const sev = vuln.severity?.toLowerCase() || 'high';
  return (
    <div className="fixed-vuln-row">
      <span className="fixed-badge">FIXED</span>
      <span className="vuln-pkg" style={{ fontSize: '0.95rem' }}>{vuln.package_name}</span>
      <span className="vuln-version">v{vuln.version}</span>
      {vuln.cve_id && <span className="vuln-cve" style={{ fontSize: '0.78rem' }}>{vuln.cve_id}</span>}
      <span className={`severity-badge badge-${sev}`} style={{ fontSize: '0.7rem', padding: '0.25rem 0.6rem' }}>{vuln.severity}</span>
    </div>
  );
}

function ScanEntry({ scan, delta, isLatest }) {
  const [open, setOpen] = useState(isLatest);
  const [filterSeverity, setFilterSeverity] = useState('all');
  const [sortBy, setSortBy] = useState('severity');

  const newVulnKeys = delta ? new Set(delta.newVulns.map(vulnKey)) : new Set();

  const filteredVulns = scan.vulnerabilities
    .filter(v => filterSeverity === 'all' || v.severity?.toLowerCase() === filterSeverity)
    .sort((a, b) => sortBy === 'severity'
      ? (SEVERITY_ORDER[a.severity?.toLowerCase()] ?? 4) - (SEVERITY_ORDER[b.severity?.toLowerCase()] ?? 4)
      : (a.package_name || '').localeCompare(b.package_name || ''));

  return (
    <div className={`scan-entry${isLatest ? ' scan-entry-latest' : ''}`}>
      <div className="scan-entry-timeline-dot" />
      <button className="scan-entry-header" onClick={() => setOpen(o => !o)}>
        <div className="scan-entry-left">
          <span className="scan-entry-date">{formatTimestamp(scan.timestamp)}</span>
          {isLatest && <span className="scan-entry-latest-tag">Latest</span>}
          <div className="scan-entry-types">
            {(scan.project_types || []).map(t => <span key={t} className="project-type-chip">{t}</span>)}
          </div>
        </div>
        <div className="scan-entry-right">
          <SeverityChips vulnerabilities={scan.vulnerabilities} />
          {delta
            ? (delta.newVulns.length === 0 && delta.fixedVulns.length === 0
              ? <span className="delta-badge delta-same">No changes</span>
              : <span className="delta-badge delta-mixed">
                  {delta.newVulns.length   > 0 && <span className="delta-part delta-part-new">+{delta.newVulns.length} new</span>}
                  {delta.fixedVulns.length > 0 && <span className="delta-part delta-part-fixed">−{delta.fixedVulns.length} fixed</span>}
                </span>)
            : <span className="delta-badge delta-baseline">Baseline</span>}
          {open ? <ChevronDown size={15} style={{ flexShrink: 0, opacity: 0.5 }} /> : <ChevronRight size={15} style={{ flexShrink: 0, opacity: 0.5 }} />}
        </div>
      </button>

      {open && (
        <div className="scan-entry-body">
          {delta && (delta.newVulns.length > 0 || delta.fixedVulns.length > 0) && (
            <div className="scan-changes">
              {delta.newVulns.length > 0 && (
                <div className="delta-section delta-section-new">
                  <div className="delta-section-title delta-section-title-new">
                    <AlertTriangle size={14} />
                    {delta.newVulns.length} new vulnerability{delta.newVulns.length !== 1 ? 'ies' : ''} introduced
                  </div>
                  <div className="vuln-grid">{delta.newVulns.map((v, i) => <VulnCard key={i} vuln={v} isNew />)}</div>
                </div>
              )}
              {delta.fixedVulns.length > 0 && (
                <div className="delta-section delta-section-fixed">
                  <div className="delta-section-title delta-section-title-fixed">
                    <CheckCircle2 size={14} />
                    {delta.fixedVulns.length} vulnerability{delta.fixedVulns.length !== 1 ? 'ies' : ''} resolved
                  </div>
                  <div className="fixed-vuln-list">{delta.fixedVulns.map((v, i) => <FixedVulnRow key={i} vuln={v} />)}</div>
                </div>
              )}
            </div>
          )}
          <div className="scan-all-vulns">
            <div className="scan-all-header">
              All vulnerabilities<span className="scan-all-count">{scan.vulnerabilities.length}</span>
            </div>
            {scan.vulnerabilities.length > 0 ? (
              <>
                <VulnFilterBar allVulns={scan.vulnerabilities} filterSeverity={filterSeverity}
                  setFilterSeverity={setFilterSeverity} sortBy={sortBy} setSortBy={setSortBy} />
                {filteredVulns.length === 0
                  ? <div className="vuln-empty">No {filterSeverity} vulnerabilities in this scan.</div>
                  : <div className="vuln-grid">{filteredVulns.map((v, i) => <VulnCard key={i} vuln={v} isNew={newVulnKeys.has(vulnKey(v))} />)}</div>}
              </>
            ) : <div className="vuln-empty">No vulnerabilities found in this scan — clean!</div>}
          </div>
        </div>
      )}
    </div>
  );
}

function RepoVulnBlock({ repoUrl, scans, onDelete, revealDelay, onReScan }) {
  const [collapsed, setCollapsed] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const sortedScans = [...scans].reverse();

  const handleDelete = async () => {
    setDeleting(true);
    try { await onDelete(repoUrl); }
    finally { setDeleting(false); setConfirmDelete(false); }
  };

  return (
    <RevealCard delay={revealDelay}>
      <div className="repo-history-block">
        <div className="repo-history-header-row">
          <button className="repo-history-header" onClick={() => setCollapsed(c => !c)}>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', minWidth: 0 }}>
              {collapsed ? <ChevronRight size={18} /> : <ChevronDown size={18} />}
              <span className="repo-history-url">{repoUrl}</span>
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexShrink: 0 }}>
              <span className="repo-history-count">{scans.length} scan{scans.length !== 1 ? 's' : ''}</span>
              <Sparkline scans={scans} />
              <TrendBadge scans={scans} />
            </span>
          </button>
          <div className="repo-delete-area">
            {onReScan && !confirmDelete && (
              <button className="repo-rescan-btn" onClick={(e) => { e.stopPropagation(); onReScan(repoUrl); }} title="Scan again">
                <Search size={12} />Scan again
              </button>
            )}
            {confirmDelete ? (
              <>
                <span className="repo-delete-confirm-text">Delete all scans?</span>
                <button className="repo-delete-btn repo-delete-confirm" onClick={handleDelete} disabled={deleting}>
                  {deleting ? <Loader2 size={13} className="loader" /> : 'Yes, delete'}
                </button>
                <button className="repo-delete-btn repo-delete-cancel" onClick={() => setConfirmDelete(false)} disabled={deleting}>Cancel</button>
              </>
            ) : (
              <button className="repo-delete-btn repo-delete-idle" onClick={() => setConfirmDelete(true)} title="Delete history">
                <Trash2 size={15} />
              </button>
            )}
          </div>
        </div>
        {!collapsed && (
          <div className="scan-timeline">
            {sortedScans.map((scan, i) => (
              <ScanEntry key={scan.timestamp} scan={scan}
                delta={sortedScans[i + 1] ? computeDelta(sortedScans[i + 1], scan) : null}
                isLatest={i === 0} />
            ))}
          </div>
        )}
      </div>
    </RevealCard>
  );
}

function PackageHistoryView({ apiFetch, onReScan }) {
  const [repos, setRepos] = useState(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState(null);
  const [search, setSearch] = useState('');

  useEffect(() => {
    apiFetch('/vuln-history')
      .then(r => { if (!r.ok) throw new Error('Failed to load vulnerability history'); return r.json(); })
      .then(data => { setRepos(data.repos); setLoading(false); })
      .catch(e => { setErr(e.message); setLoading(false); });
  }, []);

  const handleDelete = async (repoUrl) => {
    await apiFetch(`/vuln-history?repo_url=${encodeURIComponent(repoUrl)}`, { method: 'DELETE' });
    setRepos(prev => prev.filter(r => r.repo_url !== repoUrl));
  };

  const filtered = repos ? repos.filter(r => r.repo_url.toLowerCase().includes(search.toLowerCase())) : [];

  return (
    <div className="app-container">
      <header>
        <h1 className="logo"><Package size={40} color="#58a6ff" />Package History</h1>
        <p className="subtitle">Vulnerability trend across all scanned repositories — track what's introduced and what's fixed</p>
      </header>
      {loading && <SkeletonLoader />}
      {err && <div className="dashboard"><div className="status-card" style={{ borderColor: 'rgba(255,123,114,0.3)' }}>
        <div className="status-icon-wrapper" style={{ color: '#ff7b72', background: 'rgba(255,123,114,0.1)' }}><AlertTriangle size={24} /></div>
        <div className="status-info"><h3>Error</h3><p style={{ color: '#ff7b72' }}>{err}</p></div>
      </div></div>}
      {repos && repos.length === 0 && <div style={{ textAlign: 'center', color: 'var(--text-muted)', marginTop: '6rem' }}>
        <Package size={48} style={{ opacity: 0.3, marginBottom: '1rem' }} />
        <p style={{ fontSize: '1.2rem' }}>No vulnerability history yet.</p>
        <p style={{ marginTop: '0.5rem', fontSize: '0.95rem' }}>Run a scan to start tracking your vulnerability trends.</p>
      </div>}
      {repos && repos.length > 0 && (
        <>
          <div className="history-search-bar">
            <Search size={15} className="history-search-icon" />
            <input
              className="history-search-input"
              placeholder={`Search ${repos.length} repositor${repos.length !== 1 ? 'ies' : 'y'}…`}
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
            {search && <button className="history-search-clear" onClick={() => setSearch('')}>✕</button>}
          </div>
          {filtered.length === 0
            ? <div style={{ textAlign: 'center', color: 'var(--text-muted)', marginTop: '4rem' }}>
                <p>No repos match "{search}"</p>
              </div>
            : <div className="history-list">
                {filtered.map((item, i) => (
                  <RepoVulnBlock key={item.repo_url} repoUrl={item.repo_url} scans={item.scans}
                    onDelete={handleDelete} revealDelay={i * 0.07} onReScan={onReScan} />
                ))}
              </div>}
        </>
      )}
    </div>
  );
}

// ─── Main Scanner App ─────────────────────────────────────────────────────────

function ScannerApp({ apiFetch }) {
  const [repoUrl, setRepoUrl] = useState(() => localStorage.getItem('last_repo_url') || '');
  const [githubToken, setGithubToken] = useState('');
  const [isScanning, setIsScanning] = useState(false);
  const [results, setResults] = useState(null);
  const [error, setError] = useState(null);
  const [filterSeverity, setFilterSeverity] = useState('all');
  const [sortBy, setSortBy] = useState('severity');
  const [scanStatus, setScanStatus] = useState({ detect: 'idle', scanners: 'idle', ai: 'idle' });
  const [scanComplete, setScanComplete] = useState(false);
  const [scanDuration, setScanDuration] = useState(null);
  const [formSticky, setFormSticky] = useState(false);
  const sentinelRef = useRef(null);
  const scanStartRef = useRef(null);

  useEffect(() => {
    const el = sentinelRef.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => setFormSticky(!entry.isIntersecting),
      { threshold: 0, rootMargin: '-80px 0px 0px 0px' }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  useEffect(() => {
    const handler = () => {
      setResults(null);
      setError(null);
      setScanStatus({ detect: 'idle', scanners: 'idle', ai: 'idle' });
      setScanDuration(null);
    };
    window.addEventListener('app:escape', handler);
    return () => window.removeEventListener('app:escape', handler);
  }, []);

  const handleRipple = (e) => {
    if (isScanning || !repoUrl) return;
    const btn = e.currentTarget;
    const rect = btn.getBoundingClientRect();
    const ripple = document.createElement('span');
    ripple.className = 'btn-ripple';
    ripple.style.left = `${e.clientX - rect.left}px`;
    ripple.style.top = `${e.clientY - rect.top}px`;
    btn.appendChild(ripple);
    setTimeout(() => ripple.remove(), 650);
  };

  const handleScan = async (e) => {
    e.preventDefault();
    if (!repoUrl) return;
    setIsScanning(true);
    setResults(null);
    setError(null);
    setFilterSeverity('all');
    setSortBy('severity');
    setScanComplete(false);
    setScanDuration(null);
    scanStartRef.current = Date.now();
    setScanStatus({ detect: 'scanning', scanners: 'idle', ai: 'idle' });
    try {
      const response = await apiFetch('/scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ repo_url: repoUrl, github_token: githubToken }),
      });
      if (!response.ok) { const e = await response.json(); throw new Error(e.detail || 'Scan failed'); }
      setScanStatus({ detect: 'done', scanners: 'scanning', ai: 'scanning' });
      const data = await response.json();
      localStorage.setItem('last_repo_url', repoUrl);
      setResults(data);
      setScanStatus({ detect: 'done', scanners: 'done', ai: 'done' });
      setScanComplete(true);
      setScanDuration(((Date.now() - scanStartRef.current) / 1000).toFixed(1));
      setTimeout(() => setScanComplete(false), 1800);
      // Celebrate a clean result
      const vulnCount = Object.keys(data.results || {})
        .filter(k => k !== 'ai_review')
        .reduce((sum, k) => sum + (data.results[k]?.vulnerabilities?.length || 0), 0);
      if (vulnCount === 0) {
        confetti({ particleCount: 130, spread: 80, origin: { y: 0.55 },
          colors: ['#58a6ff', '#d2a8ff', '#3fb950', '#ffa657', '#ffffff'] });
      }
    } catch (err) {
      setError(err.message);
      setScanStatus({ detect: 'error', scanners: 'error', ai: 'error' });
    } finally {
      setIsScanning(false);
    }
  };

  const getStatusIcon = (s) => {
    switch (s) {
      case 'idle':     return <Box />;
      case 'scanning': return <Loader2 className="loader" />;
      case 'done':     return <CheckCircle2 />;
      case 'error':    return <XCircle />;
      default:         return <Box />;
    }
  };

  const getAllVulnerabilities = () => {
    if (!results?.results) return [];
    return Object.keys(results.results)
      .filter(k => k !== 'ai_review')
      .flatMap(k => results.results[k]?.vulnerabilities || []);
  };

  const allVulns = getAllVulnerabilities();
  const filteredAndSorted = allVulns
    .filter(v => filterSeverity === 'all' || v.severity?.toLowerCase() === filterSeverity)
    .sort((a, b) => sortBy === 'severity'
      ? (SEVERITY_ORDER[a.severity?.toLowerCase()] ?? 4) - (SEVERITY_ORDER[b.severity?.toLowerCase()] ?? 4)
      : (a.package_name || '').localeCompare(b.package_name || ''));

  const metrics = {
    total:    allVulns.length,
    critical: allVulns.filter(v => v.severity?.toLowerCase() === 'critical').length,
    high:     allVulns.filter(v => v.severity?.toLowerCase() === 'high').length,
    medium:   allVulns.filter(v => v.severity?.toLowerCase() === 'medium').length,
    low:      allVulns.filter(v => v.severity?.toLowerCase() === 'low').length,
  };

  return (
    <div className="app-container">
      {scanComplete && <div className="scan-complete-overlay" />}
      <ScanProgressBar active={isScanning} />

      <header>
        <h1 className="logo"><ShieldCheck size={40} color="#58a6ff" />SecureScan</h1>
        <p className="subtitle">Universal Security Scanner for GitHub Repositories</p>
      </header>

      <div ref={sentinelRef} style={{ height: 1, marginBottom: '-1px' }} />
      <form className={`search-container${formSticky ? ' search-form-sticky' : ''}`} onSubmit={handleScan}>
        <div className="input-wrapper">
          <Code className="input-icon" size={20} />
          <input type="url" className="repo-input" placeholder="GitHub Repository URL"
            value={repoUrl} onChange={e => setRepoUrl(e.target.value)} disabled={isScanning} required />
        </div>
        <div className="input-wrapper" style={{ maxWidth: '200px' }}>
          <Key className="input-icon" size={20} />
          <input type="password" className="repo-input" placeholder="Token (Optional)"
            value={githubToken} onChange={e => setGithubToken(e.target.value)} disabled={isScanning} />
        </div>
        <button type="submit" className={`scan-btn ${isScanning ? 'scanning' : ''}`}
          disabled={isScanning || !repoUrl} onMouseDown={handleRipple}>
          {isScanning ? <><Loader2 size={20} className="loader" /> Scanning...</> : <><Search size={20} /> Scan Repo</>}
        </button>
      </form>

      {error && (
        <div className="dashboard" style={{ marginBottom: '2rem' }}>
          <div className="status-card" style={{ borderColor: 'rgba(255,123,114,0.3)' }}>
            <div className="status-icon-wrapper" style={{ color: '#ff7b72', background: 'rgba(255,123,114,0.1)' }}><AlertTriangle size={24} /></div>
            <div className="status-info"><h3>Error Occurred</h3><p style={{ color: '#ff7b72' }}>{error}</p></div>
          </div>
        </div>
      )}

      {(isScanning || results) && !error && (
        <div className="dashboard">
          <div className="status-grid">
            <div className="status-card">
              <div className={`status-icon-wrapper status-${scanStatus.detect}`}>{getStatusIcon(scanStatus.detect)}</div>
              <div className="status-info">
                <h3>Project Detection</h3>
                <p>{scanStatus.detect === 'done' ? `Detected: ${results?.project_types?.join(', ') || 'None'}` : 'Analyzing...'}</p>
              </div>
            </div>
            {results?.project_types?.map(type => {
              if (type === 'docker') return null;
              const sr = results.results?.[type];
              return (
                <div key={type} className="status-card">
                  <div className="status-icon-wrapper status-done"><Terminal /></div>
                  <div className="status-info">
                    <h3 style={{ textTransform: 'capitalize' }}>{type} Scanner</h3>
                    <p>{sr?.vulnerabilities?.length || 0} Issues Found</p>
                  </div>
                </div>
              );
            })}
            {isScanning && scanStatus.detect === 'done' && (
              <div className="status-card">
                <div className="status-icon-wrapper status-scanning"><Loader2 className="loader" /></div>
                <div className="status-info"><h3>Deep Scan</h3><p>Auditing dependencies...</p></div>
              </div>
            )}
            <div className="status-card">
              <div className={`status-icon-wrapper status-${scanStatus.ai}`}>{getStatusIcon(scanStatus.ai)}</div>
              <div className="status-info">
                <h3>AI Code Review</h3>
                <p>{scanStatus.ai === 'done'
                  ? (results?.results?.ai_review?.status === 'error' ? `Failed (${results?.results?.ai_review?.error || 'No API Key'})` : 'Completed')
                  : (scanStatus.ai === 'scanning' ? 'Analyzing...' : 'Pending')}
                </p>
              </div>
            </div>
          </div>

          {results && (
            <>
              {scanDuration && (
                <div className="scan-duration-badge">
                  <CheckCircle2 size={13} /> Completed in {scanDuration}s
                </div>
              )}
              <div className="metrics-bar">
                <SeverityDonut critical={metrics.critical} high={metrics.high} medium={metrics.medium} low={metrics.low} />
                {[
                  { val: metrics.total,    label: 'Total Issues', cls: 'value-total' },
                  { val: metrics.critical, label: 'Critical',     cls: 'value-critical' },
                  { val: metrics.high,     label: 'High',         cls: 'value-high' },
                  { val: metrics.medium,   label: 'Medium',       cls: 'value-medium' },
                ].map(({ val, label, cls }) => (
                  <div key={label} className="metric-card">
                    <div className={`metric-value ${cls}`}><AnimatedNumber value={val} /></div>
                    <div className="metric-label">{label}</div>
                  </div>
                ))}
              </div>

              <ExportBar repoUrl={repoUrl} results={results} allVulns={allVulns} />

              {allVulns.length > 0 && (
                <RevealCard className="results-section">
                  <h2 className="section-title">
                    <FileCode2 size={24} color="#58a6ff" />
                    <span className="section-title-text">Dependency Vulnerabilities</span>
                  </h2>
                  <VulnFilterBar allVulns={allVulns} filterSeverity={filterSeverity}
                    setFilterSeverity={setFilterSeverity} sortBy={sortBy} setSortBy={setSortBy} />
                  {filteredAndSorted.length === 0
                    ? <div className="vuln-empty">No {filterSeverity} vulnerabilities found.</div>
                    : <div className="vuln-grid">{filteredAndSorted.map((vuln, i) => <VulnCard key={i} vuln={vuln} />)}</div>}
                </RevealCard>
              )}

              {results.previous_reviews?.length > 0 && (
                <RevealCard className="results-section" delay={0.1}>
                  <h2 className="section-title">
                    <History size={24} color="#d2a8ff" />
                    <span className="section-title-text">Previous AI Reviews ({results.previous_reviews.length})</span>
                  </h2>
                  {results.previous_reviews.map((review, i) => (
                    <PreviousReviewItem key={i} review={review} index={i} total={results.previous_reviews.length} />
                  ))}
                </RevealCard>
              )}

              {results.results?.ai_review?.ai_output && (
                <RevealCard className="results-section" delay={0.15}>
                  <h2 className="section-title">
                    <Bot size={24} color="#d2a8ff" />
                    <span className="section-title-text">Claude AI Review — Latest</span>
                  </h2>
                  <div className="ai-review-card">
                    <AIMarkdown>{results.results.ai_review.ai_output}</AIMarkdown>
                  </div>
                </RevealCard>
              )}

              {results.results?.ai_review?.status === 'error' && (
                <RevealCard className="results-section" delay={0.15}>
                  <h2 className="section-title">
                    <Bot size={24} color="#ff7b72" />
                    <span className="section-title-text">Claude AI Review Failed</span>
                  </h2>
                  <div className="ai-review-card" style={{ borderColor: 'rgba(255,123,114,0.3)' }}>
                    <div className="ai-content" style={{ color: '#ff7b72' }}>
                      Error: {results.results.ai_review.error || 'Unknown error occurred during AI review.'}
                    </div>
                  </div>
                </RevealCard>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Root ─────────────────────────────────────────────────────────────────────

function App() {
  const [credentials, setCredentials] = useState(() => sessionStorage.getItem('auth') || null);
  const [view, setView] = useState(() => new URLSearchParams(window.location.search).get('view') || 'scanner');
  const [toastMsg, setToastMsg] = useState(null);
  const [navHidden, setNavHidden] = useState(false);
  const toastTimer = useRef(null);
  const lastScrollY = useRef(0);
  const navigateRef = useRef(null);

  const handleLogin  = (creds) => { sessionStorage.setItem('auth', creds); setCredentials(creds); };
  const handleLogout = ()      => { sessionStorage.removeItem('auth');       setCredentials(null); setView('scanner'); };

  const navigate = (newView) => {
    setView(newView);
    window.history.pushState({}, '', newView === 'scanner' ? window.location.pathname : `?view=${newView}`);
  };
  navigateRef.current = navigate;

  const reScan = (url) => {
    localStorage.setItem('last_repo_url', url);
    navigate('scanner');
  };

  // Handle browser back/forward
  useEffect(() => {
    const onPop = () => setView(new URLSearchParams(window.location.search).get('view') || 'scanner');
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);

  // Toast notification listener
  useEffect(() => {
    const handler = (e) => {
      if (toastTimer.current) clearTimeout(toastTimer.current);
      setToastMsg(e.detail.message);
      toastTimer.current = setTimeout(() => setToastMsg(null), 2200);
    };
    window.addEventListener('app:toast', handler);
    return () => window.removeEventListener('app:toast', handler);
  }, []);

  // Hide nav on scroll down, reveal on scroll up
  useEffect(() => {
    const onScroll = () => {
      const y = window.scrollY;
      const delta = y - lastScrollY.current;
      if (delta > 10 && y > 100) setNavHidden(true);
      else if (delta < -10) setNavHidden(false);
      lastScrollY.current = y;
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  // Keyboard shortcuts
  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        navigateRef.current('scanner');
        setTimeout(() => document.querySelector('.search-container .repo-input')?.focus(), 80);
      }
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        document.querySelector('.search-container')?.requestSubmit?.();
      }
      if (e.key === 'Escape') {
        window.dispatchEvent(new CustomEvent('app:escape'));
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  // Cursor spotlight + 3D tilt for cards (event delegation — no per-card hooks needed)
  useEffect(() => {
    const onMove = (e) => {
      const card = e.target.closest('.vuln-card, .metric-card, .status-card, .repo-history-block');
      if (!card) return;
      const r = card.getBoundingClientRect();
      const xPct = (e.clientX - r.left) / r.width;
      const yPct = (e.clientY - r.top) / r.height;
      card.style.setProperty('--mx', `${(xPct * 100).toFixed(1)}%`);
      card.style.setProperty('--my', `${(yPct * 100).toFixed(1)}%`);
      if (card.classList.contains('vuln-card')) {
        const rotX = ((yPct - 0.5) * -13).toFixed(2);
        const rotY = ((xPct - 0.5) * 13).toFixed(2);
        card.style.transform = `perspective(700px) rotateX(${rotX}deg) rotateY(${rotY}deg) scale(1.025) translateY(-2px)`;
      }
    };
    const onOut = (e) => {
      const card = e.target.closest('.vuln-card, .metric-card, .status-card, .repo-history-block');
      if (card && !card.contains(e.relatedTarget)) {
        card.style.removeProperty('--mx');
        card.style.removeProperty('--my');
        if (card.classList.contains('vuln-card')) card.style.transform = '';
      }
    };
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseout', onOut);
    return () => {
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseout', onOut);
    };
  }, []);

  const apiFetch = (path, options = {}) =>
    fetch(`${API_URL}${path}`, {
      ...options,
      headers: { ...(options.headers || {}), 'Authorization': `Basic ${credentials}` },
    }).then(res => {
      if (res.status === 401) { handleLogout(); throw new Error('Session expired. Please sign in again.'); }
      return res;
    });

  return (
    <>
      <AmbientBackground />
      <Toast message={toastMsg} />
      {!credentials
        ? <LoginPage onLogin={handleLogin} />
        : <>
            <NavBar view={view} onNavigate={navigate} onLogout={handleLogout} hidden={navHidden} />
            <div className="with-nav" key={view}>
              {view === 'history'  ? <HistoryView       apiFetch={apiFetch} onReScan={reScan} />
             : view === 'packages' ? <PackageHistoryView apiFetch={apiFetch} onReScan={reScan} />
             :                       <ScannerApp         apiFetch={apiFetch} />}
            </div>
          </>
      }
    </>
  );
}

export default App;
